version: "3.8"
services:
  justice-backend:
    container_name: justice-backend
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: justice-backend:v1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}
    expose:
      - ${CONTAINER_PORT}
    volumes:
      - ./justice-backend/src/main/resources/static:/justice-backend/src/main/resources/static
    networks:
      - internalnet

networks:
  internalnet:
    name: justice-network
    external: true
