version: "3.8"
services:
  justice-backend:
    container_name: justice-backend
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: justice-backend:v1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}
    expose:
      - ${CONTAINER_PORT}
    volumes:
      - ./src/main/resources/static:/app/src/main/resources/static
    networks:
      - internalnet

  justice-backoffice:
    container_name: justice-backoffice
    build:
      context: .
    image: justice-backoffice:v1
    ports:
      - "4999:4999"
    expose:
      - 4999
    networks:
      - internalnet

networks:
  internalnet:
    name: justice-network
