server:
  port: ${CONTAINER_PORT:8081}

application:
  title: Amicale Justice
  version: 1.0.0


  ############# JWT Auth Config #########
token:
    signing:
      key: ${JWT_KEY}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

############# Google Oauth2 Config #########
  security:
    oauth2:
      resource:
        filter-order: 3

      resourceserver:
        jwt:
          jwk-set-uri: ${OUATH2_JWK_URI}
          issuer-uri: ${OAUTH2_ISSUER_URI}
          client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
          client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
          jws-algorithms: ${OAUTH_JWS_ALGORITHMS}

  ############# Database Config #########
  datasource:
    # CREATE USER 'root'@'host.docker.internal' IDENTIFIED BY '';
    #GRANT ALL PRIVILEGES ON *.* TO 'root'@'host.docker.internal' WITH GRANT OPTION;
    #FLUSH PRIVILEGES;
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  server:
    error:
      include-message: always

############# Uploads directories #########
app:
  upload:
    dir: src/main/resources/static/uploads
  conference:
    dir: src/main/resources/static/conferences
  recherche:
    dir: src/main/resources/static/recherches
  magazine:
    dir: src/main/resources/static/magazines

web:
    resources:
      static-locations: classpath:/static/,classpath:/uploads/,classpath:/conferences/,classpath:/recherches/,classpath:/magazines/
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
